spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/workspace?serverTimezone=Asia/Seoul
logging:
  level:
    com:
      example:
        workspace: debug
app:
  domain: http://localhost:8080