spring:
  application:
    name: api-artist-workspace
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/workspace?serverTimezone=Asia/Seoul
liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    com:
      example:
        workspace: debug